<?xml version="1.0" encoding="UTF-8"?><testrun name="UserRepositoryTests" project="ShopmeBackEnd" tests="8" started="8" failures="0" errors="2" ignored="0">
  <testsuite name="com.shopme.admin.user.UserRepositoryTests" time="1.588" displayname="UserRepositoryTests" uniqueid="[engine:junit-jupiter]/[class:com.shopme.admin.user.UserRepositoryTests]">
    <testcase name="testDeleteRoleEditor" classname="com.shopme.admin.user.UserRepositoryTests" time="1.058" displayname="testDeleteRoleEditor()" uniqueid="[engine:junit-jupiter]/[class:com.shopme.admin.user.UserRepositoryTests]/[method:testDeleteRoleEditor()]"/>
    <testcase name="testCreateNewUserWithTwoRoles" classname="com.shopme.admin.user.UserRepositoryTests" time="0.125" displayname="testCreateNewUserWithTwoRoles()" uniqueid="[engine:junit-jupiter]/[class:com.shopme.admin.user.UserRepositoryTests]/[method:testCreateNewUserWithTwoRoles()]">
      <error>org.springframework.dao.DataIntegrityViolationException: could not execute statement [Duplicate entry 'ravi@gmail.com' for key 'users.UK6dotkott2kjsp8vw4d0m25fb7'] [insert into users (email,enabled,first_name,last_name,password,photos) values (?,?,?,?,?,?)]; SQL [insert into users (email,enabled,first_name,last_name,password,photos) values (?,?,?,?,?,?)]; constraint [users.UK6dotkott2kjsp8vw4d0m25fb7]&#13;
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:290)&#13;
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:241)&#13;
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)&#13;
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)&#13;
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:335)&#13;
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:160)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)&#13;
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:165)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)&#13;
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)&#13;
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:223)&#13;
	at jdk.proxy2/jdk.proxy2.$Proxy120.save(Unknown Source)&#13;
	at com.shopme.admin.user.UserRepositoryTests.testCreateNewUserWithTwoRoles(UserRepositoryTests.java:48)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	Suppressed: org.springframework.transaction.UnexpectedRollbackException: Transaction silently rolled back because it has been marked as rollback-only&#13;
		at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:804)&#13;
		at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:758)&#13;
		at org.springframework.test.context.transaction.TransactionContext.endTransaction(TransactionContext.java:135)&#13;
		at org.springframework.test.context.transaction.TransactionalTestExecutionListener.afterTestMethod(TransactionalTestExecutionListener.java:260)&#13;
		at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:487)&#13;
		at org.springframework.test.context.junit.jupiter.SpringExtension.afterEach(SpringExtension.java:278)&#13;
		... 2 more&#13;
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement [Duplicate entry 'ravi@gmail.com' for key 'users.UK6dotkott2kjsp8vw4d0m25fb7'] [insert into users (email,enabled,first_name,last_name,password,photos) values (?,?,?,?,?,?)]&#13;
	at org.hibernate.dialect.MySQLDialect.lambda$buildSQLExceptionConversionDelegate$3(MySQLDialect.java:1234)&#13;
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)&#13;
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)&#13;
	at org.hibernate.id.insert.GetGeneratedKeysDelegate.performMutation(GetGeneratedKeysDelegate.java:116)&#13;
	at org.hibernate.engine.jdbc.mutation.internal.MutationExecutorSingleNonBatched.performNonBatchedOperations(MutationExecutorSingleNonBatched.java:47)&#13;
	at org.hibernate.engine.jdbc.mutation.internal.AbstractMutationExecutor.execute(AbstractMutationExecutor.java:55)&#13;
	at org.hibernate.persister.entity.mutation.InsertCoordinatorStandard.doStaticInserts(InsertCoordinatorStandard.java:194)&#13;
	at org.hibernate.persister.entity.mutation.InsertCoordinatorStandard.coordinateInsert(InsertCoordinatorStandard.java:132)&#13;
	at org.hibernate.persister.entity.mutation.InsertCoordinatorStandard.insert(InsertCoordinatorStandard.java:95)&#13;
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:85)&#13;
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:670)&#13;
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:291)&#13;
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:272)&#13;
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:322)&#13;
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:391)&#13;
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:305)&#13;
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:224)&#13;
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:137)&#13;
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:175)&#13;
	at org.hibernate.event.internal.DefaultPersistEventListener.persist(DefaultPersistEventListener.java:93)&#13;
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:77)&#13;
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:54)&#13;
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)&#13;
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:757)&#13;
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:741)&#13;
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:319)&#13;
	at jdk.proxy2/jdk.proxy2.$Proxy114.persist(Unknown Source)&#13;
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:625)&#13;
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)&#13;
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:277)&#13;
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)&#13;
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)&#13;
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)&#13;
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)&#13;
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)&#13;
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:173)&#13;
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:148)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:379)&#13;
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)&#13;
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:138)&#13;
	... 11 more&#13;
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'ravi@gmail.com' for key 'users.UK6dotkott2kjsp8vw4d0m25fb7'&#13;
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)&#13;
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)&#13;
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:912)&#13;
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1054)&#13;
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1003)&#13;
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1312)&#13;
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:988)&#13;
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)&#13;
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)&#13;
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:194)&#13;
	... 55 more&#13;
&#13;
</error>
    </testcase>
    <testcase name="testListAllUsers" classname="com.shopme.admin.user.UserRepositoryTests" time="0.177" displayname="testListAllUsers()" uniqueid="[engine:junit-jupiter]/[class:com.shopme.admin.user.UserRepositoryTests]/[method:testListAllUsers()]"/>
    <testcase name="testCreateUser" classname="com.shopme.admin.user.UserRepositoryTests" time="0.138" displayname="testCreateUser()" uniqueid="[engine:junit-jupiter]/[class:com.shopme.admin.user.UserRepositoryTests]/[method:testCreateUser()]"/>
    <testcase name="testDeleteUser" classname="com.shopme.admin.user.UserRepositoryTests" time="0.034" displayname="testDeleteUser()" uniqueid="[engine:junit-jupiter]/[class:com.shopme.admin.user.UserRepositoryTests]/[method:testDeleteUser()]"/>
    <testcase name="testGetUserById" classname="com.shopme.admin.user.UserRepositoryTests" time="0.016" displayname="testGetUserById()" uniqueid="[engine:junit-jupiter]/[class:com.shopme.admin.user.UserRepositoryTests]/[method:testGetUserById()]"/>
    <testcase name="testUpdateUserRoles" classname="com.shopme.admin.user.UserRepositoryTests" time="0.012" displayname="testUpdateUserRoles()" uniqueid="[engine:junit-jupiter]/[class:com.shopme.admin.user.UserRepositoryTests]/[method:testUpdateUserRoles()]">
      <error>java.util.NoSuchElementException: No value present&#13;
	at java.base/java.util.Optional.get(Optional.java:143)&#13;
	at com.shopme.admin.user.UserRepositoryTests.testUpdateUserRoles(UserRepositoryTests.java:77)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testUpdateUserDetails" classname="com.shopme.admin.user.UserRepositoryTests" time="0.013" displayname="testUpdateUserDetails()" uniqueid="[engine:junit-jupiter]/[class:com.shopme.admin.user.UserRepositoryTests]/[method:testUpdateUserDetails()]"/>
  </testsuite>
</testrun>
